### PR TITLE
Addition of various functions

### PR DESCRIPTION
**Pull request by atuy1219**
The app will be multilingual (only Japanese for now)
It's now compatible with Android 15
Add support for the predictive back gesture

### CODE REVIEW

**Comment by atuy1219** [comment]
Regarding multilingualization, I think it would be best to use Crowdin or similar in the end.

**Comment by samolego** [comment]
Thank you so much!

I'm currently away on holiday, so this will need to wait a bit.

Is crowdin hard to setup? Never done that before 😅 .

**Comment by atuy1219** [comment]
Unfortunately, I haven't used Crowdin either.
I apologize for not being of more help.

**Comment by samolego** [comment]
That's ok! I'll see how it goes by myself then :)

**Comment by atuy1219** [comment]
Please ignore commit 6b19f21 (create build.yml) as it is incorrect  .

**Pull request merged**
