### PR TITLE
Introduced version catalog for streamlined dependency management

### PR DESCRIPTION
**Pull request by CodeWithTamim**
This pull request integrates a version catalog (libs.versions.toml) to centralize dependency management within the project. By utilizing this approach, we enhance dependency consistency, reduce maintenance overhead, and facilitate version updates across multiple modules. This change provides a more organized and efficient way to manage project dependencies. I'm really happy to put my first pull request on Canta. Thank you :)

### CODE REVIEW

**Comment by CodeWithTamim** [comment]
c'mon man where are you @samolego

**Comment by samolego** [comment]
Hi, sorry, I overlooked this!

**Review by samolego — APPROVED** [review]

**Comment by samolego** [comment]
This is really noce, thank you for your contribution!

**Comment by CodeWithTamim** [comment]
> Hi, sorry, I overlooked this!

thanks man

**Pull request merged**
